# Generated by Django 5.1.3 on 2025-03-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certifications',
            field=models.URLField(blank=True),
        ),
    ]
