# Generated by Django 5.1.3 on 2025-03-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
