# Generated by Django 5.1.3 on 2025-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_statement',
            field=models.CharField(max_length=250),
        ),
    ]
