# Generated by Django 5.1.3 on 2025-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_personal_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_training_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='soft_skills_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='technical_skills_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteer_experience_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience_point',
            field=models.JSONField(default=list),
        ),
    ]
