# Generated by Django 5.1.3 on 2025-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_additional_training_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_statement',
            field=models.CharField(max_length=300),
        ),
    ]
